# Generated by Django 3.1.3 on 2021-01-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_category_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
